### ISSUE TITLE
crash: chunk read failed

### ISSUE THREAD

**Issue by ChillerDragon** [KurtThiemann/thanos-in-place#3]
```
[1/3][248010/515347] ../Lasergurkenland/world/DIM-1/region/r.13.55.mca
PHP Fatal error:  Uncaught Exception: Failed to save region file to /tmp/thanosBdtqaA: chunk read failed in /home/chiller/Desktop/git/thanos-in-place/vendor/aternos/thanos/src/Region/AnvilRegion.php:238
Stack trace:
#0 /home/chiller/Desktop/git/thanos-in-place/vendor/aternos/thanos/src/Region/AnvilRegion.php(157): Aternos\Thanos\Region\AnvilRegion->writeToFile()
#1 /home/chiller/Desktop/git/thanos-in-place/src/InPlaceThanos.php(50): Aternos\Thanos\Region\AnvilRegion->save()
#2 /home/chiller/Desktop/git/thanos-in-place/thanos.php(30): InPlaceThanos->snap()
#3 {main}
  thrown in /home/chiller/Desktop/git/thanos-in-place/vendor/aternos/thanos/src/Region/AnvilRegion.php on line 238
 ```
  
 This is a hand patched version so line numbers do not add up.
 
 ```
 $ git diff
diff --git a/src/InPlaceThanos.php b/src/InPlaceThanos.php
index 1852107..bf1367a 100644
--- a/src/InPlaceThanos.php
+++ b/src/InPlaceThanos.php
@@ -6,13 +6,34 @@ class InPlaceThanos extends \Aternos\Thanos\Thanos
 {
     public function snap(AnvilWorld $world): int
     {
+        global $got_sig_int;
+
         $removedChunks = 0;
         $output = tempnam(sys_get_temp_dir(), 'thanos');
 
+        $totalDir = count($world->getRegionDirectories());
+        $currentDir = 0;
         foreach ($world->getRegionDirectories() as $regionDirectory) {
             $forcedChunks = $this->getForceLoadedChunks($regionDirectory);
+            $totalRegionFiles = count($regionDirectory->getRegionFiles());
+            $totalRegionFilesLength = strlen((string)$totalDir);
+            $currentRegionFile = 1;
+            $currentDir += 1;
             foreach ($regionDirectory->getRegionFiles() as $regionFile) {
                 $regionFile = $regionDirectory->getPath() . DIRECTORY_SEPARATOR . $regionFile;
+                if ($currentRegionFile % 10 == 0 || $currentRegionFile == $totalRegionFiles) {
+                        echo sprintf('[%d/%d][%*d/%*d] %s',
+                        $currentDir,
+                        $totalDir,
+                        $totalRegionFilesLength,
+                        $currentRegionFile,
+                        $totalRegionFilesLength,
+                        $totalRegionFiles,
+                        $regionFile
+                    );
+                    echo PHP_EOL;
+                }
+                $currentRegionFile += 1;
                 $region = new \Aternos\Thanos\Region\AnvilRegion($regionFile, $output);
                 foreach ($region->getChunks() as $chunk) {
                     if(in_array([$chunk->getGlobalXPos(), $chunk->getGlobalYPos()], $forcedChunks, true)) {
@@ -47,3 +68,4 @@ class InPlaceThanos extends \Aternos\Thanos\Thanos
         return $removedChunks;
     }
 }
+
 ```
 
 The disk is not full. CPU, ram etc all is endless on this machine. So I doubt it was a hiccup on my machine.
 Not sure if this is possibly a upstream issue in thanos tho.
 
I attached the region file that seemed to have caused the crash. Maybe it is also corrupted and that is the issue.
[crashing_region_file.zip](https://github.com/KurtThiemann/thanos-in-place/files/11198050/crashing_region_file.zip)

So I assumed the region file is corrupted moved it to my local test setup and did try a region fixer as follows:

```
$ python regionfixer.py ../../git/wipe_lgl/world/DIM-1/region/r.13.58.mca  --fc

Welcome to Region Fixer!
(v 0.3.6)


############################################################
############## Scanning separate region files ##############
############################################################

1 of 1|##########################################################################################################################################|Time: 0:00:01

Chunk problems:
------------------------------
| Problem | Corrupted  Total |
------------------------------
|  Count  |     1       999  |
------------------------------

Region problems:
No problems found.




######### Repairing chunks with status: Corrupted ##########
Repairing chunks in regionset "selected region files":
    Repaired 0 chunks in this regionset.


Repaired 0 chunks with status: Corrupted
```

I changed the print output to print on every file so one can see which exactly crashed it but as you can see it still crashes
```
[1/2][1/1] ../world//DIM-1/region/r.13.58.mca
PHP Fatal error:  Uncaught Exception: Failed to save region file to /tmp/thanosUIFmhp: chunk read failed in /home/chiller/Desktop/git/wipe_lgl/thanos-in-place/vendor/aternos/thanos/src/Region/AnvilRegion.php:238
Stack trace:
#0 /home/chiller/Desktop/git/wipe_lgl/thanos-in-place/vendor/aternos/thanos/src/Region/AnvilRegion.php(156): Aternos\Thanos\Region\AnvilRegion->writeToFile()
#1 /home/chiller/Desktop/git/wipe_lgl/thanos-in-place/src/InPlaceThanos.php(43): Aternos\Thanos\Region\AnvilRegion->save()
#2 /home/chiller/Desktop/git/wipe_lgl/thanos-in-place/thanos.php(30): InPlaceThanos->snap()
#3 {main}
  thrown in /home/chiller/Desktop/git/wipe_lgl/thanos-in-place/vendor/aternos/thanos/src/Region/AnvilRegion.php on line 238
[chiller@arch ~/Desktop/git/wipe_lgl/thanos-in-place]$ ./thanos.php ../world/
[1/2][1/1] ../world//DIM-1/region/r.13.58.mca
PHP Fatal error:  Uncaught Exception: Failed to save region file to /tmp/thanos3Sb5Wn: chunk read failed in /home/chiller/Desktop/git/wipe_lgl/thanos-in-place/vendor/aternos/thanos/src/Region/AnvilRegion.php:238
Stack trace:
#0 /home/chiller/Desktop/git/wipe_lgl/thanos-in-place/vendor/aternos/thanos/src/Region/AnvilRegion.php(156): Aternos\Thanos\Region\AnvilRegion->writeToFile()
#1 /home/chiller/Desktop/git/wipe_lgl/thanos-in-place/src/InPlaceThanos.php(43): Aternos\Thanos\Region\AnvilRegion->save()
#2 /home/chiller/Desktop/git/wipe_lgl/thanos-in-place/thanos.php(30): InPlaceThanos->snap()
#3 {main}
  thrown in /home/chiller/Desktop/git/wipe_lgl/thanos-in-place/vendor/aternos/thanos/src/Region/AnvilRegion.php on line 238
 ```

**Comment by KurtThiemann** [comment]
Region Fixer reported a corrupted chunk, so I think thanos is behaving as intended here.
It is not intended for thanos to somehow interpret or fix broken chunks. 

You could probably work round this by just wrapping the whole content of the `$regionDirectory->getRegionFiles() as $regionFile` in a try catch statement, so corrupted region files are skipped. If you decide to do this, there isn't really a reason to create a pr. This repo really was just meant as an example and I don't think anyone else is ever going to use it, so the best option for you would be to just maintain your own fork.
